server:
    port: 8080

# logging:
#   level:
#     org:
#       springframework:
#         security: DEBUG

spring:
    # security:
    #     user:
    #       name: admin
    #       password: admin
    cloud:
        gateway:
          routes:
          - id: user_service
            uri: http://localhost:8081/
            
            predicates:
            - Path=/**
            # - Path=/api/student/**
            # - Path=/api/teacher/**
            # - Path=/api/admin/**