server:
    port: 8080
logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG

    reactor:
        netty: INFO
    org:
      springframework:
        cloud:
            gateway: INFO


# logging:
#   level:
#     org:
#       springframework:
#         security: DEBUG

spring:
    # security:
    #     user:
    #       name: admin
    #       password: admin
    cloud:
        gateway:
          routes:
          - id: user_service
            uri: http://localhost:8090/
            
            predicates:
            - Path=/api/**
            # - Path=/api/student/**
            # - Path=/api/teacher/**
            # - Path=/api/admin/**
            filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}